version: "3.7"

volumes:
  mysql-data:

services:
  storemanagement:
    image: storemanagement
    ports:
      - 8484:8082
    depends_on:
      - mysqlcon

  medical:
    image: medical
    ports:
      - 8383:8282
    depends_on:
      - mysqlcon

  mysqlcon:
    image: mysql
    environment:
      - MYSQL_DATABASE=clinicdb
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql-data:/var/lib/mysql
