version: "3.9" 

services:
  storemanagment :
    image: docker158/storemanagement
    ports:
      - 8484:8082
    depends_on:
      - mysqlcon

  medicalfile:
    image: docker158/medical
    ports:
      - 8383:8282
    depends_on:
      - mysqlcon

  mysqlcon:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clinicdb
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data: